name: Java CI

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'adopt'
        java-home: 'C:\\Java\\jdk-22.0.1'  # Specify the path to your JDK installation

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
